name: Releases next branch # Update to trigger action
on:
  workflow_dispatch:
  push:
    branches:
      - next

jobs:
  Next_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20.x'

      - name: Install
        run: yarn

       # Dry run - `yarn lerna version --no-git-tag-version --no-push`
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn lerna publish --canary --preid canary --dist-tag canary --yes